### ISSUE TITLE
SDK does not support Polygon network.

### ISSUE THREAD

**Issue by bin0316** [ProjectOpenSea/opensea-js#480] opened 2022-04-20 18:39 UTC
const seaport = new OpenSeaPort(provider, {
  networkName: Network.Main,
  apiKey: YOUR_API_KEY
})
It is for Ethereum mainnet.
I want to know that how to set networkName when I create seaport on Polygon network.

**Comment by shenhaoguangDayDayUp** [comment] 2022-04-21 00:13
I have same problem .

**Comment by esteban-OpenSea** [comment] 2022-06-10 01:54
Thank you for your feedback, we are working on this.

In the meantime, check these out:

- https://support.opensea.io/hc/en-us/articles/4404029357587-How-do-I-create-and-sell-NFTs-on-Polygon-
- https://docs.opensea.io/docs/polygon-basic-integration

**Comment by Daudxu** [comment] 2022-08-10 03:56
I have same problem .

**Comment by onurozansahin** [comment] 2022-08-30 07:46
Hello @esteban-OpenSea , when can we expect Polygon support to be available? Even a rough timeline would help a lot 🙌

**Comment by fedecastelli** [comment] 2023-02-24 16:53
I have the same problem. Are there any news?

**Comment by Madalosso** [comment] 2023-02-24 17:10
> I have the same problem. Are there any news?

As afaik there's no eta for polygon support, I drop this SDK in favor of using [Reservoir](https://reservoir.tools/)

**Comment by StevenJ59** [comment] 2023-02-26 23:17
> > I have the same problem. Are there any news?
> 
> As afaik there's no eta for polygon support, I drop this SDK in favor of using [Reservoir](https://reservoir.tools/)

lol but reservoir don't work for polygon...

**Comment by sahinhakan** [comment] 2023-05-11 11:07
Polygon and Mumbai networks still not supported?

**Comment by numpde** [comment] 2023-05-15 11:49
Dear maintainers,

I hope this message finds you well. I am a user of the OpenSea.js library, and I have been greatly satisfied with the functionalities it provides so far. It has been a fantastic tool that has made my work with NFTs much more efficient and enjoyable.

However, I have recently again run into a bit of a roadblock, as I noticed that there is no support for the Polygon network in the OpenSea.js library. As you might know, the Polygon network has been rapidly gaining popularity due to its scalability and efficiency, and many developers, including myself, are increasingly building and deploying applications on this network.

I am sure that I am not alone in saying that Polygon support in OpenSea.js would be a much-appreciated addition. It would open up new possibilities for us developers and would undoubtedly contribute to the growth and versatility of the NFT ecosystem as a whole.

I understand that maintaining and extending a library such as OpenSea.js is a complex task and involves careful planning and prioritization. However, I would be extremely grateful if you could give us an idea of when we might expect Polygon network support to be added to OpenSea.js.

Thank you for your continuous efforts in developing and maintaining this valuable resource. Your work is greatly appreciated by the community.

**Comment by ryanio** [comment] 2023-06-09 01:16
closing as duplicate of #150

**Closed by ryanio** 2023-06-09 01:16 UTC
Labels: dev-feature-request
