### ISSUE TITLE
Error: API Error 400: Invalid request: "['Wyvern orders posted to the API are deprecated, except for shared storefront orders']"

### ISSUE THREAD

**Issue by cto-aarchik** [ProjectOpenSea/opensea-js#629] opened 2022-06-28 12:42 UTC
error while createSellOrder using opensea-js 4.0.3

**Comment by cterech** [comment] 2022-06-28 13:50
@cto-aarchik can you provide some more details? what type of listing are you trying to create?

**Comment by Lebski** [comment] 2022-06-28 14:26
Duplicate of Duplicate of https://github.com/ProjectOpenSea/opensea-js/issues/610

**Closed** 2022-06-30 21:05 UTC
