### ISSUE TITLE
Error 500 when listing

### ISSUE THREAD

**Issue by lehongvo** [ProjectOpenSea/opensea-js#1264] opened 2023-10-30 04:55 UTC
### Component

API

### Have you ensured that all of these are up to date?

- [X] opensea-js
- [X] Node (minimum v16)

### What version of opensea-js are you on?

6.1.11

### What function is the bug in?

handleSDKEvents

### Operating System

None

### Describe the bug

When we attempt to create a listing or cancel an existing one, an error message with code 500 is displayed. This situation is similar to what occurs on the opensea.io app. However, it's important to note that the listing or update process still completes successfully. The issue lies in the fact that the 'handleSDKEvents' function does not return any data.

<img width="1049" alt="image" src="https://github.com/ProjectOpenSea/opensea-js/assets/71160314/04992300-6f0e-42ad-be31-1f4e8965b145">

**Comment by lehongvo** [comment] 2023-10-31 02:52
@ryanio please check this issue

**Comment by ryanio** [comment] 2023-11-07 19:44
if you can give specific steps to recreate i can try to help you further but otherwise i don't have any information to help debug further for you

**Comment by ryanio** [comment] 2023-11-13 19:28
closing since details on reproducing the error is not given

**Closed by ryanio** 2023-11-13 19:28 UTC
Labels: bug
