### ISSUE TITLE
Error: API Error 400: You cannot access body after reading from request's data stream

### ISSUE THREAD

**Issue by xuqiong2020** [ProjectOpenSea/opensea-js#585] opened 2022-06-18 09:09 UTC
https://testnets-api.opensea.io/v2/orders/rinkeby/seaport/listings   推送createSellOrder 订单异常

**Comment by plondon** [comment] 2022-06-18 17:02
Duplicate of https://github.com/ProjectOpenSea/opensea-js/issues/565

**Closed** 2022-06-24 07:55 UTC
