### ISSUE TITLE
The offerer does not have the amount needed to create or fulfill. when 

### ISSUE THREAD

**Issue by Mohin-Php** [ProjectOpenSea/opensea-js#1209] opened 2023-09-29 13:56 UTC
### Component

API, Utils

### Have you ensured that all of these are up to date?

- [X] opensea-js
- [x] Node (minimum v16)

### What version of opensea-js are you on?

2.0.7

### What function is the bug in?

createBuyOrder

### Operating System

Linux

### Describe the bug

```
  const provider = new ethers.providers.Web3Provider(window.ethereum);
            const openseaSDK = new OpenSeaSDK(provider, {
                chain: Chain.Goerli,
            });
            const offer = await openseaSDK.createBuyOrder({
                asset: {
                    tokenId: "57",//property(token id)
                    tokenAddress: "0x843fac3d5c70680ae9134863cc0d1b7d853e7f36",//collection(address)
                    tokenStandard: "ERC721", // TokenStandard. If omitted, defaults to 'ERC721'. Other options include 'ERC20' and 'ERC1155'
                },
                accountAddress: provider.provider.selectedAddress,
                startAmount: 0.0001,//property (amount)
            });
```

in my wallet I have 0.02 eth in my goerli chain but i am getting this type of error 
The offerer does not have the amount needed to create or fulfill.
when i try with a different wallet it works perfectly.
both wallet are on goerli chain

**Comment by ryanio** [comment] 2023-09-29 13:59
You need WETH for offers since it cannot take ETH out of your account.

**Comment by Mohin-Php** [comment] 2023-09-29 14:25
@ryanio 
thx for reply
i have WETH as well in my account but it still giving me error

**Comment by ryanio** [comment] 2023-10-04 00:53
@Mohin-Php what is the account address?

**Comment by ryanio** [comment] 2023-10-10 23:59
Closing for now since a bug cannot be identified or reproduced

**Closed by ryanio** 2023-10-10 23:59 UTC
Labels: bug
