### ISSUE TITLE
[getAsset] Floor price always 0

### ISSUE THREAD

**Issue by wizardlabsxyz** [ProjectOpenSea/opensea-js#1033] opened 2023-06-09 01:24 UTC
When calling V1 getAsset the collection object that is also returned always has 0 as the floor price. It seems to not fetch the data right.

https://api.opensea.io/api/v1/asset/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/1/?include_orders=false

When calling V1 getCollection the response has the right floor price 

https://api.opensea.io/api/v1/collection/boredapeyachtclub

**Comment by wizardlabsxyz** [comment] 2023-06-09 01:25
I realize this an issue with the API and not the SDK but I idk how to create an issue for the API.

**Comment by JoshuaSchmidt-OpenSea** [comment] 2023-06-09 04:44
This is intentional. The floor price returned in the getAsset endpoint is on a deprecation path. During deprecation, we set it to 0 to be backwards compatible to current serializers.

getCollection is the correct replacement for getting the floor price.

**Comment by ryanio** [comment] 2023-06-11 21:19
thanks joshua for the details, closing as resolved as the intended behavior

**Closed by ryanio** 2023-06-11 21:19 UTC
