### ISSUE TITLE
Error in `getOrder` if token has id `0`

### ISSUE THREAD

**Issue by sxurik** [ProjectOpenSea/opensea-js#157] opened 2021-09-02 08:49 UTC
This code:
```js
const order = await seaport.api.getOrder({
  asset_contract_address: '0x9af18ae321386085aa287723f64eb640694b0a13',
  token_id: '0',
})
```
fails with this error message:
![image](https://user-images.githubusercontent.com/32016927/131812568-a7c0f784-575d-40fc-ab6f-e069c1ca86f9.png)

Retrieving orders for other tokens on the same contract works fine.

The same is true for API:
- [this call](https://api.opensea.io/wyvern/v1/orders?asset_contract_address=0x9af18ae321386085aa287723f64eb640694b0a13&token_id=0) fails (`token_id` is `0`);
- [this one](https://api.opensea.io/wyvern/v1/orders?asset_contract_address=0x9af18ae321386085aa287723f64eb640694b0a13&token_id=2) returns orders as expected (`token_id` is `2`).

Getting an _asset_ with id `0` for some reason doesn't have the same problem.

**Comment by roadmanfong** [comment] 2021-09-09 07:26
This issues seems happened in restful api

I can view   [https://testnets.opensea.io/assets/0xee39caaecfa2975d724789c2a3957ba2a93052a3/0](https://testnets.opensea.io/assets/0xee39caaecfa2975d724789c2a3957ba2a93052a3/0)

but I can't get order from api

```cmd
curl --request GET \
     --url 'https://rinkeby-api.opensea.io/wyvern/v1/orders?asset_contract_address=0xee39caaecfa2975d724789c2a3957ba2a93052a3&bundled=false&include_bundled=false&include_invalid=false&token_id=0&limit=20&offset=0&order_by=created_date&order_direction=desc' \
     --header 'Accept: application/json'
```

**Comment by rokkit** [comment] 2021-09-16 13:39
If change parameters like this, all start to work:

* rename "token_id" to "token_ids"
* move "token_ids" to first place, before "asset_contract_address"

```
curl --request GET \
     --url 'https://rinkeby-api.opensea.io/wyvern/v1/orders?token_ids=0&asset_contract_address=0xee39caaecfa2975d724789c2a3957ba2a93052a3&bundled=false&include_bundled=false&include_invalid=false&limit=20&offset=0&order_by=created_date&order_direction=desc' \
     --header 'Accept: application/json'
```

But this isn't fix for lib usage

**Comment by Rotemy** [comment] 2022-03-06 21:46
Totally agree, can we get a fix for this?

**Comment by esteban-OpenSea** [comment] 2022-04-19 15:14
Hey, are you still having issues with this?

**Comment by dyordan1** [comment] 2022-05-01 22:01
Bumping. This bug is still present, at least on Rinkeby api. Easy to reproduce:

`token_id=1` works:
https://testnets-api.opensea.io/wyvern/v1/orders/?asset_contract_address=0xefC7a57a4ad949240dd9B777344EEc7CBDf234bD&limit=20&offset=0&side=1&token_id=1

`token_id=0` does not:
https://testnets-api.opensea.io/wyvern/v1/orders/?asset_contract_address=0xefC7a57a4ad949240dd9B777344EEc7CBDf234bD&limit=20&offset=0&side=1&token_id=0

`token_ids=0` does:
https://testnets-api.opensea.io/wyvern/v1/orders/?asset_contract_address=0xefC7a57a4ad949240dd9B777344EEc7CBDf234bD&limit=20&offset=0&side=1&token_ids=0

I'll switch over to token_ids for now, but this seems like it should be a simple fix. I'm assuming something somewhere treats 0 as unset, but the list `[0]` is fine since it's not empty.

**Comment by sxurik** [comment] 2023-05-24 05:24
Doesn't seem to be fixed.

**Comment by ryanio** [comment] 2023-06-09 01:11
@sxurik can you give examples?

**Comment by ryanio** [comment] 2023-06-11 21:18
i just tried your code in the opening post (api keys removed):


```js
const { OpenSeaSDK, Chain } = require("opensea-js");
const { ethers } = require("ethers");

const main = async () => {
  const provider = new ethers.providers.JsonRpcProvider(
    "https://eth-mainnet.g.alchemy.com/v2/"
  );

  const opensea = new OpenSeaSDK(provider, {
    chain: Chain.Mainnet,
    apiKey: "",
  });

  const order = await opensea.api.getOrder({
    asset_contract_address: "0x9af18ae321386085aa287723f64eb640694b0a13",
    token_id: "0",
  });

  console.log(order);
};

main();
```

and it worked for me, outputting a valid order:

```js
{
  createdDate: '2023-06-11T21:16:43.105955',
  closingDate: '2023-06-12T01:46:21',
  listingTime: 1686518186,
  expirationTime: 1686534381,
  orderHash: '0x7e11f44bcd60968456e625757181b3e6d84f9f3646a71bcd7d03b4a9173a65f9',
  maker: {
    address: '0x0cade9f0baa0d2b83ef33a2be686e460f8dc23f7',
    config: '',
    profileImgUrl: 'https://storage.googleapis.com/opensea-static/opensea-profile/33.png',
    user: { username: undefined }
  },
  taker: null,
  protocolData: {
    parameters: {
      offerer: '0x0cade9f0baa0d2b83ef33a2be686e460f8dc23f7',
      offer: [Array],
      consideration: [Array],
      startTime: '1686518186',
      endTime: '1686534381',
      orderType: 1,
      zone: '0x0000000000000000000000000000000000000000',
      zoneHash: '0x0000000000000000000000000000000000000000000000000000000000000000',
      salt: '0x11cc880de6467c5d1292936a6d1d9208',
      conduitKey: '0x0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000',
      totalOriginalConsiderationItems: 3,
      counter: 0
    },
    signature: null
  },
  protocolAddress: '0x00000000000000adc04c56bf30ac9d3c0aaf14dc',
  currentPrice: BigNumber { _hex: '0x0116e35586de4000', _isBigNumber: true },
  makerFees: [],
  takerFees: [
    { account: [Object], basisPoints: '250' },
    { account: [Object], basisPoints: '50' }
  ],
  side: 'bid',
  orderType: 'basic',
  cancelled: false,
  finalized: false,
  markedInvalid: false,
  clientSignature: undefined,
  makerAssetBundle: {
    maker: null,
    assets: [ [Object] ],
    assetContract: undefined,
    name: null,
    slug: null,
    description: null,
    externalLink: null,
    permalink: null
  },
  takerAssetBundle: {
    maker: null,
    assets: [ [Object] ],
    assetContract: undefined,
    name: null,
    slug: null,
    description: null,
    externalLink: null,
    permalink: null
  }
}
```

if you are still having issues please open a new issue with details on how to reproduce. thanks.

**Closed by ryanio** 2023-06-11 21:18 UTC
Labels: dev-api-bug
