### ISSUE TITLE
[Bug] mismatch person property profile_img_url and profileImgUrl

### ISSUE THREAD

**Issue by KagamiChan** [ProjectOpenSea/opensea-js#119] opened 2021-06-24 11:01 UTC
In the code we declare it as `profileImgUrl`
https://github.com/ProjectOpenSea/opensea-js/blob/84a4e811e020e98945749157075514047079bc72/src/types.ts#L214

but from the API we actually get `profile_img_url`:
![image](https://user-images.githubusercontent.com/3816900/123252095-7e527380-d51e-11eb-90f4-9b92cd054f2e.png)

example
https://api.opensea.io/wyvern/v1/orders?limit=20&offset=0

**Comment by sayhicoelho** [comment] 2021-08-14 00:07
We've another issue: the `profile_img_url` value is wrong.

The user image:
![image](https://user-images.githubusercontent.com/8188365/129428252-3c68e9dc-1f12-487b-84a3-d7b7cf5ca76b.png)

The OpenSea API value:
![image](https://user-images.githubusercontent.com/8188365/129428276-cbf8249e-12fc-4f65-8e2c-a731c2c6b55d.png)

It points to:
https://storage.googleapis.com/opensea-static/opensea-profile/22.png

and not to:
https://lh3.googleusercontent.com/xpLPhSqUADRZCb7l20LLH2nYiiNwWgJszYyYFh_az8x4SWbKhd-uB39SH-nA7y1xiC0dmHg58UOKHPr8CvdGLAMEqHESmQYrIsSULA=s0

**Comment by esteban-OpenSea** [comment] 2022-03-30 22:49
`profile_img_url` is displays the owner of that NFT's profile picture. If you are looking to get the image of the NFT you need to look at `image_url`. Refer to `[this.](https://docs.opensea.io/reference/asset-object)` Closing this ticket since it's not a bug/issue.

**Closed by esteban-OpenSea** 2022-03-30 22:49 UTC
Labels: doc issue
