### ISSUE TITLE
NPM install throws git error

### ISSUE THREAD

**Issue by dcarlcf** [ProjectOpenSea/opensea-js#9] opened 2018-12-06 18:32 UTC
I ran NPM install, but it failed with the following error:

```
code 1
npm ERR! Command failed: /usr/bin/git submodule update -q --init --recursive
npm ERR! error: The following untracked working tree files would be overwritten by checkout:
npm ERR! 	.gitattributes
npm ERR! 	.gitignore
npm ERR! 	LICENSE
npm ERR! 	README.md
npm ERR! Please move or remove them before you switch branches.
npm ERR! Aborting
npm ERR! Unable to checkout '91ee5d23072fd5c1e62bb78eb6d8fa335098ee5f' in submodule path 'src/wyvern-ethereum/utxo-merkle-proof'
npm ERR! Failed to recurse into submodule path 'src/wyvern-ethereum'
```
I tried it in a different project and on a different computer as well and got the same error. Any thoughts on why this might be happening?

**Comment by alexanderatallah** [comment] 2018-12-07 20:30
Wasn't able to reproduce this, but it should be fixed in version `0.4.0-rc8`, which removes all submodules. Can you confirm?

**Comment by dcarlcf** [comment] 2018-12-07 20:33
Yes, I will confirm shortly, thank you for looking into it!

**Comment by alexanderatallah** [comment] 2018-12-08 00:31
Looks like it worked, so marking this closed!

**Closed by alexanderatallah** 2018-12-08 00:31 UTC

**Comment by dcarlcf** [comment] 2018-12-08 00:35
Thanks for your help!
