### ISSUE TITLE
does the sdk support  polygon network?

### ISSUE THREAD

**Issue by myst4** [ProjectOpenSea/opensea-js#662] opened 2022-07-11 17:40 UTC
hello there I was wondering is this sdk is actually supporting polygon blockchain?

I cant found any related this in the docs

thanks!

**Comment by onurozansahin** [comment] 2022-08-13 10:03
It would have made an awesome change if SDK started supporting Polygon. When can we expect this? Or can we expect this at all?

**Comment by ashitosh03** [comment] 2023-01-24 13:18
Hello, is there any plan adding support for Polygon network?

**Comment by ryanio** [comment] 2023-05-23 19:02
we are planning to add more of our supported networks soon

**Comment by ryanio** [comment] 2023-06-09 01:16
closing as duplicate of #150

**Closed by ryanio** 2023-06-09 01:16 UTC
