### ISSUE TITLE
React/Next applications do not work after building

### ISSUE THREAD

**Issue by UnioDex** [ProjectOpenSea/opensea-js#451] opened 2022-03-31 10:25 UTC
```js
  const handleBurn = useCallback(async () => {
    const ethersWeb3 = new ethers.providers.Web3Provider(window.ethereum);
    await ethersWeb3.send("eth_requestAccounts", []);
    const signer = ethersWeb3.getSigner();
    const address = await signer.getAddress();
    try {
      const seaport = new OpenSeaPort(ethersWeb3.provider, {
        networkName:
          selectedNetwork.chainId === 1 ? Network.Main : Network.Rinkeby,
      });

      const assets = [
        {
          tokenId: 5528,
          tokenAddress: selectedNetwork.mainContractAddress,
        },
      ];

      const transactionHash = await seaport.transferAll({
        assets,
        fromAddress: address,
        toAddress: "0x000000000000000000000000000000000000dEaD",
      });
    } catch (e) {
      console.error(`Error while burning: ${e.message}`);
      console.error(e);
    }
  }, []);
```

I created a simple NFT transfer script in React and it works perfectly in the development mode. However, after I build the project, `provider_utils.ts` file of `@0x/utils` throws an error:

```
App.js:66 TypeError: Cannot read properties of undefined (reading 'then')
    at Object.i.includes.t.sendAsync (provider_utils.ts:89:39)
    at bound  (util.js:647:16)
    at e.<anonymous> (web3_wrapper.ts:782:32)
    at u (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at utils.ts:51:114
    at new Promise (<anonymous>)
    at s (utils.ts:51:114)
    at e.value (web3_wrapper.ts:769:41)
```

I tried both React.js and Next.js. React 17, and React 18, tried different webpack configurations, I tried using Web3.js, ethers.js but none of it worked.

My latest package.json:
```json
{
  "name": "redacted",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@chakra-ui/react": "^1.8.6",
    "@emotion/react": "^11",
    "@emotion/styled": "^11",
    "@fontsource/barlow": "^4.5.5",
    "@fontsource/saira": "^4.5.5",
    "@fontsource/saira-condensed": "^4.5.5",
    "@testing-library/jest-dom": "^5.16.3",
    "@testing-library/react": "^12.1.4",
    "@testing-library/user-event": "^13.5.0",
    "@walletconnect/web3-provider": "^1.7.7",
    "browserslist": "^4.20.2",
    "ethers": "^5.6.2",
    "framer-motion": "^6",
    "got": "^12.0.3",
    "node-polyfill-webpack-plugin": "^1.1.4",
    "opensea-js": "^3.0.2",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-scripts": "5.0.0",
    "walletlink": "^2.5.0",
    "web-vitals": "^2.1.4",
    "web3modal": "^1.9.5"
  },
  "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "assert": "^2.0.0",
    "buffer": "^6.0.3",
    "crypto-browserify": "^3.12.0",
    "https-browserify": "^1.0.0",
    "os-browserify": "^0.3.0",
    "process": "^0.11.10",
    "react-app-rewired": "^2.2.1",
    "stream-browserify": "^3.0.0",
    "stream-http": "^3.2.0",
    "url": "^0.11.0"
  }
}
```

config.overrides.js (webpack):
```js
const webpack = require("webpack");

module.exports = function override(config) {
  const fallback = config.resolve.fallback || {};
  Object.assign(fallback, {
    crypto: require.resolve("crypto-browserify"),
    stream: require.resolve("stream-browserify"),
    assert: require.resolve("assert"),
    http: require.resolve("stream-http"),
    https: require.resolve("https-browserify"),
    os: require.resolve("os-browserify"),
    url: require.resolve("url"),
    fs: false,
    path: false,
  });
  config.resolve.fallback = fallback;
  config.plugins = (config.plugins || []).concat([
    new webpack.ProvidePlugin({
      process: "process/browser",
      Buffer: ["buffer", "Buffer"],
    }),
  ]);
  return config;
};
```

This problem might be not opensea-js related and might be @0xproject/tools related. Or maybe this is a problem with React/Webpack but I didn't know where to open this issue since I'm not sure. Any help is appreciated.

**Comment by weiliang903** [comment] 2022-03-31 10:35
Similar problem, the development environment is OK, but the resources after the build report an error.
env:
```shell
"next": "12.1.0",
```

**Comment by weiliang903** [comment] 2022-03-31 10:54
I tried different versions of opensea-js, including v3.0.2, v3.0.1, v3.0.0, v2.0.2, and finally only the last version of 2.x(`v2.0.2 `) working.

**Comment by UnioDex** [comment] 2022-03-31 11:22
> I tried different versions of opensea-js, including v3.0.2, v3.0.1, v3.0.0, v2.0.2, and finally only the last version of 2.x(`v2.0.2 `) working.

In 2.0.2 I'm having this error:
```
TypeError: os.type is not a function
    at new XMLHttpRequest (xml-http-request.ts:102:1)
    at HttpProvider.prepareRequest (httpprovider.js:61:1)
    at HttpProvider.sendAsync (httpprovider.js:116:1)
    at RequestManager.sendAsync (requestmanager.js:80:1)
    at Eth.send [as call] (method.js:141:1)
    at SolidityFunction.call (function.js:140:1)
    at promisify.ts:15:1
    at new Promise (<anonymous>)
    at Object.<anonymous> (promisify.ts:11:1)
    at step (interval_utils.ts:3:1)
```

**Comment by UnioDex** [comment] 2022-03-31 12:31
I returned back to the Next.js project, downgraded to 2.0.2, removed node_modules, package.json and .next files/folders and now the problem has been solved! Thanks for the tip @weiliang903! I hope this can be solved with the new version as well.

**Comment by esteban-OpenSea** [comment] 2022-03-31 22:49
Thanks for pointing this out to us! We are looking into this! For now, downgrading is a good way to continue working on your project. But we will work on getting this fixed for the new version!

**Comment by ludovitkapusta** [comment] 2022-04-07 21:25
im getting this error after building project through webpack with production mode

from this, after digging deeper, i found that this is PROBABLY caused by webpacks minimizing through Terser plugin.

so far, didnt find solution, just using non-minized version for now

**Comment by JeroenJADS** [comment] 2022-04-25 19:25
@UnioDex Facing similar issues when using the Opensea-js SDK in react;
I'm using Opensea-js 2.0.2 with the exact same config.overrides. Have you changed anything additionally in the package.json you shared that might have helped solve this issue? 

Thanks in advance!


<img width="550" alt="Screenshot 2022-04-25 at 21 21 51" src="https://user-images.githubusercontent.com/58403194/165159232-73e6c1cc-af5b-4369-9de1-b08295416923.png">

**Comment by UnioDex** [comment] 2022-04-25 19:28
Here is what I did to fix the issue:
- Moved to Next.js
- Removed node_modules folder
- Added this to package.json:
```
  "browser": {
    "fs": false,
    "path": false
  }
```
- Edited next.config.js to be like this:
```
module.exports = {
    reactStrictMode: true,
    productionBrowserSourceMaps: false,
    webpack: (config, {}) => {
        config.resolve.fallback = {
            ...config.resolve.fallback,
            fs: false
        };
        return config;
    }
};
```

@JeroenJADS you are probably still using opensea.js 3.0+ because this error shouldn't happen in v2. You need to remove your node_modules

**Comment by JeroenJADS** [comment] 2022-04-26 08:30
Thanks so much for the reply @UnioDex. In hindsight the problem was that I was using Web3.js as an OpenSea provider. As I switched to Ether.js it did work as intended. It looks like OpenSea-js@2.0.2 does work if you use Ether.js like you did in your example. 

Is this the same confirmation screen your users are getting though if you are requesting the transfer? This looks hella scammy imo.


<img width="359" alt="Screenshot 2022-04-26 at 10 29 17" src="https://user-images.githubusercontent.com/58403194/165257167-0875328c-0b64-4552-8ae2-8a9b2e4a27ea.png">

**Comment by JeroenJADS** [comment] 2022-04-26 08:35
Thanks so much for your response @UnioDex . The problem I faced was due to the fact that I was using Web3.js as an OpenSea provider. As I switched to Ether.js like in your shared code it did work as intended when I downgraded to opensea-js@2.0.2. Thanks a bunch.

Is this the same confirmation screen as you are getting for your users though as you suggest a transfer? Looks hella scammy imo haha.


<img width="350" alt="confirmation" src="https://user-images.githubusercontent.com/58403194/165258270-cb7e0967-0ddb-432e-8494-1a6ad77b3d5f.png">

**Comment by UnioDex** [comment] 2022-04-26 09:47
@JeroenJADS Hahah not really. It might be related to something else

**Comment by mwelche** [comment] 2022-05-11 00:46
Faced this issue as well with 3.0.4 on a fresh next-js project and downgrading to 2.0.2 fixed it. thanks @weiliang903.

> I tried different versions of opensea-js, including v3.0.2, v3.0.1, v3.0.0, v2.0.2, and finally only the last version of 2.x(`v2.0.2 `) working.

**Comment by theboxer** [comment] 2022-05-11 12:11
Have this issue as well, v3.0.0 works, anything above throws `cannot read properties of undefined (reading 'then')` when trying to create an offer

**Comment by asghaier76** [comment] 2022-05-30 18:16
Any update on whether this has been fixed or not?

**Comment by asghaier76** [comment] 2022-06-02 13:47
Hi @esteban-OpenSea any update on when this fix will be released

**Comment by jgarcie** [comment] 2022-06-07 16:22
@esteban-OpenSea just checking to see if there were any updates?

**Comment by asghaier76** [comment] 2022-06-08 20:14
anyone faced this same issue in Angular and was able to resolve it by downgrading to 3.0.0 or 2.0.2

**Comment by dwasyluk** [comment] 2022-06-16 16:34
Any updates on this? Major blocker for our team here and a bit disappointing to see the lack of response from the OpenSea team. Ping @esteban-OpenSea 🙏 we've exhausted all possible options for remediating ourselves, need official team support to get this fixed please.

**Comment by esteban-OpenSea** [comment] 2022-06-16 18:27
Did this work for some of you? https://github.com/ProjectOpenSea/opensea-js/issues/451#issuecomment-1108955151

Also, many of you are mentioning it only works after downgrading. Is this still the case?

Also, I would recommend joining our Discord where active members of the community are online and can help troubleshoot in realtime https://discord.com/channels/397566282729390110/434175585745633280

**Comment by mwelche** [comment] 2022-06-16 19:14
This is still an issue with the latest version 4.0.1. This is a big problem for us as we can not upgrade to the new seaport

**Comment by jtaaa** [comment] 2022-06-17 21:05
Just linked a PR that should fix this issue for clients using `npm`. Unfortunately it doesn't fix the issue for `yarn` users but those users can try adding a temporary resolution to their `package.json` to use a patched version of `@0x/utils`
```
  "resolutions": {
    "@0x/utils": "https://github.com/ProjectOpensea/0x-tools/raw/provider-patch/utils/0x-utils-6.5.0.tgz"
  }
```

**Closed** 2022-06-20 13:24 UTC
Labels: question, dev-sdk-bug
