### ISSUE TITLE
NPM Packages for 4.0.19 and 4.0.20 doesn't seem to have been rebuild?

### ISSUE THREAD

**Issue by SMLaursen** [ProjectOpenSea/opensea-js#869] opened 2023-03-09 11:44 UTC
After upgrading to 4.0.19 and 4.0.20 I kept getting "Unsupported Protocol", when looking into **sdk.js**, I realized that it doesn't look like it have been re-transpiled?

From https://www.npmjs.com/package/opensea-js?activeTab=explore;
![image](https://user-images.githubusercontent.com/7354598/224014413-dcb3ea75-9dd9-44a7-b6be-f3f129ce26d7.png)

**Comment by reaganchisholm** [comment] 2023-03-09 17:48
Looks and older version of the code got published to NPM under a new version tag. The [current sdk.ts in this repo](https://github.com/ProjectOpenSea/opensea-js/blob/master/src/sdk.ts#L1038-L1040) calls the `isValidProtocol()` function which was added in 4.0.18 (#863) but is not present in 4.0.20

**Comment by JoshuaSchmidt-OpenSea** [comment] 2023-03-09 18:09
I pushed version 4.0.21 and confirmed the method is in the NPM package explorer.
https://www.npmjs.com/package/opensea-js?activeTab=explore

**Comment by JoshuaSchmidt-OpenSea** [comment] 2023-03-09 18:10
Please reopen this issue if version 4.0.21 has the same problem

**Comment by pi9min** [comment] 2023-03-10 00:50
@JoshuaSchmidt-OpenSea  @cterech 

Hello.

I have confirmed that isValidProtocol is included in 4.0.21, but in the just released 4.0.22, it seems to be back to the old code again.
Therefore, the `Unsupported Protocol` is occurring again in the latest version. We apologize for the inconvenience, but we would appreciate it if you could check the code again.

Thanks.

**Comment by JoshuaSchmidt-OpenSea** [comment] 2023-03-10 01:04
We have tracked down the root cause of this churn. Sorry for the inconvenience. I will fix the latest.

**Comment by JoshuaSchmidt-OpenSea** [comment] 2023-03-10 02:15
This should be fixed (again) in version 4.0.23

**Closed by JoshuaSchmidt-OpenSea** 2023-03-10 02:15 UTC

**Comment by nickfujita** [comment] 2023-03-10 04:42
@JoshuaSchmidt-OpenSea Thanks for working to fix this, but there appears to still be an issue with the npm deploy. Originally the `lib` folder contained all the compiled js code, where the `main` pointer in your root `package.json` is `lib/index.js`. However, the most recent deploy now contains the `src` folder and a copy of `package.json` in the `lib` folder. This is causing our build process to fail because it can not find the module files.

I manually edited my local `node_modules` to move the files in `lib/src` into `lib`, and it seems to have the updated code. Could you please make this correction?

**Comment by JoshuaSchmidt-OpenSea** [comment] 2023-03-10 14:33
@nickfujita The correction has been made to the latest version
