### ISSUE TITLE
{ code: -32603, message: "execution reverted" } when try to buy NFT

### ISSUE THREAD

**Issue by creed-dev** [ProjectOpenSea/opensea-js#756] opened 2022-09-27 12:11 UTC
I get an error `{ code: -32603, message: "execution reverted" }` from console when try to buy nft which was put up for sale through the OpenSeaSDK through createSellOrder function. If put it up for sale through the UI, there is no such problem.

Code:
```
require('dotenv').config();
const opensea = require("opensea-js");
const Network = require("opensea-js").Network;
const OpenSeaSDK = opensea.OpenSeaSDK;
const HDWalletProvider = require("@truffle/hdwallet-provider");
const {WyvernSchemaName} = require('opensea-js/lib/types');

const MNEMONIC = process.env.MNEMONIC;
const NODE_API_KEY = process.env.INFURA_KEY || process.env.ALCHEMY_KEY;
const NFT_CONTRACT_ADDRESS = process.env.NFT_CONTRACT_ADDRESS;
const OWNER_ADDRESS = process.env.OWNER_ADDRESS;
const NETWORK = process.env.NETWORK;
const API_KEY = process.env.API_KEY || ""; // API key is optional but useful if you're doing a high volume of requests.

const provider = new HDWalletProvider({
    mnemonic: MNEMONIC,
    providerOrUrl: "https://" + NETWORK + ".infura.io/v3/" + NODE_API_KEY,
    chainId: 5
});

const seaport = new OpenSeaSDK(
    provider,
    {
        networkName: Network.Goerli
    },
    (arg) => console.log(arg)
);

async function listing(tokenId) {
    try {
        await seaport.createSellOrder({
            asset: {
                tokenId: tokenId,
                tokenAddress: NFT_CONTRACT_ADDRESS,
                schemaName: WyvernSchemaName.ERC721
            },
            startAmount: .001,
            accountAddress: OWNER_ADDRESS
        });

        return "Success!";
    } catch (err) {
        return err;
    }
}

listing("0").then(res => {
    console.log(res);
}).catch(rej => {
    console.log(rej);
});
```

package.json:
```
{
  "type": "commonjs",
  "dependencies": {
    "@truffle/hdwallet-provider": "^2.0.15",
    "axios": "^0.27.2",
    "dotenv": "^16.0.2",
    "ethers": "^5.7.1",
    "opensea-js": "^4.0.12",
    "web3": "^1.8.0",
    "wyvern-schemas": "^0.6.15"
  }
}
```
Node version: v16.17.1

**Comment by carlosbalsas** [comment] 2022-09-29 10:24
+1

**Comment by CokeBear666** [comment] 2022-09-29 13:29
+1

**Comment by cterech** [comment] 2022-09-29 13:56
hey - acknowledging the issue, we will look at prioritizing the fix in the next few weeks

**Comment by relipa-dev** [comment] 2022-09-30 03:59
+ 1

**Comment by maxtor3569** [comment] 2022-10-05 16:07
+1

**Comment by qnft-mjb** [comment] 2022-10-05 22:54
Still receiving this error, any update?

**Comment by qnft-mjb** [comment] 2022-10-09 14:34
Not a contributor, but in my working through of trying to solve this I discovered something. This function appears to use wyvern protocol, which is deprecated. Seaport-js package has a function createOrder that should be used to make seaport protocol orders.

**Comment by tantannguyen9x** [comment] 2022-10-13 07:18
+1 This bug is more than 1 month old, when will there be a fix for this bug?

**Comment by Smeagolworms4** [comment] 2022-10-13 08:26
If not fix, Do you have a workaround to solve the problem?

**Comment by qnft-mjb** [comment] 2022-10-14 01:10
To my understanding, createBuyOrder post orders to the wyvern protocol smart contract. This contract is no longer by used by opensea for orders so even if this bug was resolved the orders posted would not appear on opensea(or anywhere?) - opensea  is now using the the seaport contract and to interact with that you need to use seaport-js sdk ... And yes sadly it is more complex.

**Comment by Smeagolworms4** [comment] 2022-10-14 15:06
The method is createShellOrder and not createBuyOrder. (Maybe it's a name mistake in your answer).
Do you have an example of using createOrder?
However, I did not find the reference to Wyvern on the createShellOrder method.

**Comment by qnft-mjb** [comment] 2022-10-14 16:04
Sorry, my issue originated with createBuyOrder and this ticket is for createSellOrder... The error code is the same though...

Again, I am not a contributor and can't confirm this... But the order model you post with this function is designed for wyvern. The create listing/offer api endpoints on Opensea now only accept a seaport order model. Or at least I didn't see any way to successfully list a wyvern order on Opensea.

So to my knowledge, no work around... Ya gotta upgrade 🤷

**Comment by Smeagolworms4** [comment] 2022-10-16 09:34
Thank you for your answer.  On the other hand I have no problem to upgrade because I use openseajs only to make a create sell order.  but how do I upgrade with what?  do you have an example?

**Comment by qnft-mjb** [comment] 2022-10-16 12:33
So there are two issues 0xAskar has posted that have helped me. More discussion on it exists in the comments.

[https://github.com/ProjectOpenSea/seaport/discussions/594]()

[https://github.com/ProjectOpenSea/seaport/issues/600]()

Seaport orders are a little different. If you go Opensea Discord - dev resources channel, there is a video called "seaport workshop" in this they explain the order model.

But you need to use seaport-js (check the readme) to generate and fulfill orders (this will be on chain) - these orders are decoupled from Opensea it's self. Any marketplace can hook up to seaport.

But seaport was developed by OS, they are the main consumer of seaport orders. However they don't list automatically on OS you need write code that first uses seaport-js to produce a signed order, then make a API request (V2 on OS docs) to list the order ( offer = bid, listing = ask) - I don't believe opensea-js ask has a V2 function yet.

Hope this helps.

**Comment by inartin** [comment] 2022-10-18 18:59
Is it still not solved? I even noticed that if I create the order via SDK as usual, this error will appear even on the main OpenSea site.

**Comment by Smeagolworms4** [comment] 2022-10-19 09:32
Still not and I haven't been able to find a workaround. Or a fix.
+1

**Comment by alandotcom** [comment] 2022-10-20 03:26
Try this when listing for sale:

```js
  openseaSDK.seaport.createOrder = async (input) => {
    const override = {
      restrictedByZone: false,
      allowPartialFills: false,
    };

    const newInput = { ...input, ...override };

    return await ogCreate.call(openseaSDK.seaport, newInput);
  };
```

**Comment by Smeagolworms4** [comment] 2022-10-20 07:25
Thank you very mush @alandotcom 

```javascript

const { Seaport } = require('@opensea/seaport-js/lib/seaport');

const oldCreateOrder = Seaport.prototype.createOrder;
Seaport.prototype.createOrder = function (input) {
	return oldCreateOrder.call(this, {
		...input,
		...{
			restrictedByZone: false,
			allowPartialFills: false,
		}
	});
};
```

Works for me

**Comment by inartin** [comment] 2022-10-23 10:17
> Works for me

So it works if using Seaport SDK directly, so creating/accepting orders via seaport, but what if using OpenSea SDK?

**Comment by creed-dev** [comment] 2022-10-24 07:03
> Try this when listing for sale:
> 
> ```js
>   openseaSDK.seaport.createOrder = async (input) => {
>     const override = {
>       restrictedByZone: false,
>       allowPartialFills: false,
>     };
> 
>     const newInput = { ...input, ...override };
> 
>     return await ogCreate.call(openseaSDK.seaport, newInput);
>   };
> ```

This works for me. Thank you, @alandotcom !

**Closed** 2022-10-24 07:05 UTC

**Comment by Smeagolworms4** [comment] 2022-10-24 13:12
This bug is not closed. The solution has hack for fix. Not final solution @creed-dev

**Comment by inartin** [comment] 2022-10-25 08:14
> The solution has hack for fix. Not final solution

Agree, this should be fixed at the SDK level not as a workaround.

**Comment by hoanggjang33889** [comment] 2022-11-09 04:19
It seems to me that this error is caused by the goreli . contract
https://etherscan.io/address/0x1e0049783f008a0085193e00003d00cd54003c71
![image](https://user-images.githubusercontent.com/18367105/200737308-04f8f44f-b047-458c-9e6c-04cefea70e22.png)
